/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * NewFrame4.java
 *
 * Created on 06.06.2012, 16:29:14
 */
package de.htw;

import java.awt.TextArea;

import de.uni_trier.jane.service.network.link_layer.LinkLayer_async;
import de.uni_trier.jane.service.operatingSystem.RuntimeOperatingSystem;

/**
 *
 * @author chrech
 */
public class ChatFrame extends java.awt.Frame {
	
	private ChatService chatService;

    /** Creates new form ChatFrame */
    public ChatFrame() {
        initComponents();
    }
    
    public ChatFrame(ChatService chatService) {
        initComponents();
        this.chatService = chatService;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chatTextArea = new java.awt.TextArea("", 0, 0, TextArea.SCROLLBARS_VERTICAL_ONLY);
        chatTextArea.setEditable(false);
        messageTextField = new java.awt.TextField();
        sendButton = new java.awt.Button();
        sendButton.setActionCommand("send-msg");
        sendButton.setName("sendButton");
        contactList = new java.awt.List();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        add(chatTextArea, java.awt.BorderLayout.CENTER);
        add(messageTextField, java.awt.BorderLayout.SOUTH);

        sendButton.setLabel("send");
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        add(sendButton, java.awt.BorderLayout.NORTH);
        add(contactList, java.awt.BorderLayout.WEST);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
    	System.out.println("CLICK:" + evt);
    	String message = this.messageTextField.toString();
    	String destination = this.contactList.getSelectedItem();
    	chatService.sendMessage(message, destination);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ChatFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.TextArea chatTextArea;
    private java.awt.List contactList;
    private java.awt.TextField messageTextField;
    private java.awt.Button sendButton;
    // End of variables declaration//GEN-END:variables
}
